### ISSUE TITLE
Change global JSON properties to use FMID names instead of 'common' names

### ISSUE THREAD

**Issue by mikefultonbluemix** [mikefultonbluemix/zbrew#24]
We have a mix right now of names, where we use things like COBOL but also CEE.
Let's switch to use FMID names to ensure we won't have collisions. 
Names are: HMQ (HL/ASM), CEE (LE), IGY (COBOL), CIC (CICS), 

https://www.ibm.com/support/knowledgecenter/SSENW6_1.6.0/com.ibm.hlasm.v1r6.asm/asmi1023.pdf

https://www.ibm.com/support/knowledgecenter/SSGMCP_5.1.0/com.ibm.cics.ts.devtrial.doc/topics/prog_dir.pdf

**Comment by gkeuken** [comment]
Pull request #55 addressed this change for zbrew
