### ISSUE TITLE
Set up base image with core PTFs in pre-req products and necessary tools

### ISSUE THREAD

**Issue by mikefultonbluemix** [mikefultonbluemix/zbrew#28]
At a minimum:
-add LE PTFs for COBOL 6.3
-add curl 
-add any PTFs necessary for dbb, Debug Tool, rse

**Comment by mikefultonbluemix** [comment]
If we move to z/OS 2.4 image on the zPDT on zLinux dev/test environments, the LE PTFs and perhaps most of the other PTFs goes close to zero.
We need curl for the CI/CD system. If it's a hassle, we can manually set it up

**Comment by gkeuken** [comment]
z/OS 2.4 System setup 
Hostname: TORZDT1.CANLAB.IBM.COM
TN3270 Port: 7023
SSH Port: 7022
