### ISSUE TITLE
smpchkptf and smpchksw incorrectly report missing PTFs

### ISSUE THREAD

**Issue by gkeuken** [mikefultonbluemix/zbrew#47]
The issue is we run through all target zones of a CSI looking for PTFs .. in the case of HLASM for ADCD we specify MVS.GLOBAL.CSI which is where HLASM is BUT this CSI also contains a target zone for CSQ911. When smpchkptf doesn't find HLASM ptfs in the CSQ911 target zone we incorrectly report this as missing PTFs even though they are successfully found in the MVST target zone of the same CSI. We are going to need some OR type logic when scanning a CSI that has multiple target zones.   Note this didn't show up in my DEMOs or earlier testing because I removed the CSQ911 target zones from the MVS.GLOBAL.CSI (helps speed things up). I discovered this during testing on a un-modified z/OS 2.4 ADCD system.

**Comment by mikefultonbluemix** [comment]
@gkeuken when #27 is complete, can you add the particular smpchksw command i should run to highlight this problem? I'm not sure what PTFs I should be searching for, nor the FMID to specify

**Comment by gkeuken** [comment]
it appears this is no longer an issue with smpchksw .. closing issue !
