### ISSUE TITLE
Unable to specify Directory Blocks for PDS

### ISSUE THREAD

**Issue by gkeuken** [mikefultonbluemix/zbrew#63]
During Accept processing a failure occurred due to insufficient directory blocks on a PDS.
dtouch currently does not provide function to specify directory blocks for PDS and default of 5 is insufficient. 

This is a ZOAU issue but opening issue here for tracking.

**Comment by mikefultonbluemix** [comment]
@gkeuken can we close this now?

**Comment by gkeuken** [comment]
yep
